dist: trusty
sudo: required
language: rust

env:
  global:
    - RUST_BACKTRACE=1

os:
  - linux

rust:
  - stable
  - beta
  - nightly

matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    rust: stable
  - os: linux
    arch: arm64
    rust: stable

env:
  global:
  - RUST_BACKTRACE=1

cache: false

before_script:
  - rustup default nightly-2019-12-20
  - rustup component add rustfmt-preview
  - rustup component add clippy

script:
  - make clippy
  - cargo fmt --all -- --check
  - cargo build
  - cargo test --all
