dist: trusty
sudo: required
language: rust

os:
  - linux

arch:
  - amd64
  - arm64

rust:
  - stable
  - beta
  - nightly

matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    rust: stable
  - os: linux
    arch: arm64

env:
  global:
  - RUST_BACKTRACE=1

cache: false

before_script:
  - rustup default nightly-2019-09-05
  - rustup component add rustfmt-preview
  - rustup component add clippy

script:
  - make clippy
  - cargo fmt --all -- --check
  - cargo build
  - cargo test --all
